<!DOCTYPE html>
<html lang="fr">
























































































































































































</html></body></div>  Référence séance : {{ $seance->id }}  Ce rapport a été généré automatiquement par le système K Beauty Smart Mirror – {{ now()->format('d/m/Y à H:i') }}<br><div class="footer"></div>  @endif  </div>    </div>      @endforeach        @endif        </div>          <div class="photo-label">{{ $photo->zone ?? 'cuir chevelu' }}</div>          <img src="{{ url('storage/' . $photo->chemin_serveur) }}" alt="Après">        <div class="photo-item">        @if($photo->chemin_serveur)      @foreach($photosApres as $photo)    <div class="photos-grid">    <div class="section-title">Photos Après Soin ({{ $photosApres->count() }})</div>  <div class="section {{ $photosAvant->isNotEmpty() ? 'page-break' : '' }}">  @if($photosApres->isNotEmpty())  {{-- Photos après --}}  @endif  </div>    </div>      @endforeach        @endif        </div>          <div class="photo-label">{{ $photo->zone ?? 'cuir chevelu' }}</div>          <img src="{{ url('storage/' . $photo->chemin_serveur) }}" alt="Avant">        <div class="photo-item">        @if($photo->chemin_serveur)      @foreach($photosAvant as $photo)    <div class="photos-grid">    <div class="section-title">Photos Avant Soin ({{ $photosAvant->count() }})</div>  <div class="section">  @if($photosAvant->isNotEmpty())  {{-- Photos avant --}}  @endif  </div>    </ul>      @endforeach        <li>{{ $nom }}</li>      @foreach($diag['produits_recommandes'] ?? [] as $nom)      @endforeach        <li>{{ $produit->nom }}@if($produit->prix) — {{ number_format($produit->prix, 2) }} €@endif</li>      @foreach($seance->produitsRecommandes as $produit)    <ul class="produits-list">    <div class="section-title">Produits Recommandés</div>  <div class="section">  @if($seance->produitsRecommandes->isNotEmpty() || !empty($diag['produits_recommandes']))  {{-- Produits recommandés --}}  @endif  </div>    <p style="font-size: 10pt; line-height: 1.6;">{{ $seance->note_seance }}</p>    <div class="section-title">Note du Praticien</div>  <div class="section">  @if($seance->note_seance)  {{-- Note praticien --}}  @endif  </div>    @endif    <div class="commentaire">"{{ $diag['commentaire'] }}"</div>    @if(!empty($diag['commentaire']))    </div>      </div>        </table>          </tbody>            @endforeach            </tr>              <td>{{ ucfirst($cat['niveau'] ?? '') }}</td>              </td>                <div class="score-bar"><div class="score-fill" style="width: {{ $cat['score'] }}%"></div></div>                {{ $cat['score'] }}/100              <td>              <td>{{ $cat['nom'] }}</td>            <tr>            @foreach($diag['categories'] ?? [] as $cat)          <tbody>          </thead>            <tr><th>Indicateur</th><th>Score</th><th>Niveau</th></tr>          <thead>        <table class="diag-table">      <div style="flex: 1;">      </div>        <div class="score-global-label">Score global de santé capillaire</div>        <div class="score-global">{{ $diag['score_global'] ?? '–' }}<span style="font-size:14pt">/100</span></div>      <div>    <div style="display: flex; gap: 20px; align-items: center; margin-bottom: 16px;">    <div class="section-title">Analyse IA du Cuir Chevelu</div>  <div class="section">  @if($diag)  @endphp    $diag = $diagPhoto?->diagnostic_ia;    $diagPhoto = $seance->photos->whereNotNull('diagnostic_ia')->sortByDesc('phase')->first();    $photosApres = $seance->photos->where('phase', 'apres')->values();    $photosAvant = $seance->photos->where('phase', 'avant')->values();  @php  {{-- Analyse capillaire + score global --}}  </div>    </div>      </div>        <div class="info-row"><span class="info-label">Praticien :</span> {{ $seance->miroir?->nom ?? 'Miroir' }}</div>        @endif        <div class="info-row"><span class="info-label">Téléphone :</span> {{ $seance->cliente->telephone }}</div>        @if($seance->cliente?->telephone)        @endif        <div class="info-row"><span class="info-label">Email :</span> {{ $seance->cliente->email }}</div>@if($seance->cliente?->email)<div></div>@endif<div class="info-row"><span class="info-label">Sexe :</span> {{ $seance->cliente->sexe }}</div>@if($seance->cliente?->sexe)@endif<div class="info-row"><span class="info-label">Date de naissance :</span> {{ \Carbon\Carbon::parse($seance->cliente->date_de_naissance)->format('d/m/Y') }}</div>@if($seance->cliente?->date_de_naissance)<div class="info-row"><span class="info-label">Nom :</span> {{ $seance->cliente?->prenom }} {{ $seance->cliente?->nom }}</div>
<div>
    <div class="info-grid">
        <div class="section-title">Informations Cliente</div>
        <div class="section"> {{-- Informations cliente --}}
            <div class="content"></div>
        </div>{{ $seance->date_debut?->format('H:i') }} – {{ $seance->date_fin?->format('H:i') ?? 'En cours' }}Séance du {{ $seance->date_debut?->format('d/m/Y') }}<br>
        <div style="text-align: right; font-size: 9pt; opacity: 0.8;"></div>
        <div class="boutique">{{ $seance->boutique?->nom }}</div>
        <h1>BILAN K BEAUTY</h1>
        <div>
            <div class="header">

                <body>
                    </head>
                    </style>.page-break { page-break-before: always; }.footer { margin-top: 30px; padding: 12px 30px; background: #f8f8f8; font-size: 8pt; color: #999; text-align: center; border-top: 1px solid #eee; }.produits-list li::before { content: "• "; color: #daa520; }.produits-list li { padding: 4px 0; font-size: 10pt; }.produits-list { list-style: none; margin-top: 8px; }.commentaire { background: #fafafa; border-left: 3px solid #daa520; padding: 10px 14px; font-size: 10pt; line-height: 1.6; font-style: italic; margin-top: 8px; }.score-global-label { font-size: 9pt; color: #666; text-align: center; }.score-global { font-size: 24pt; font-weight: bold; color: #daa520; text-align: center; padding: 16px; } .score-fill { height: 100%; background: #daa520; border-radius: 3px; } .score-bar { height: 6px; background: #eee; border-radius: 3px; overflow: hidden; margin-top: 2px; } .diag-table td { padding: 5px 8px; border-bottom: 1px solid #eee; } .diag-table th { background: #f5f5f5; text-align: left; padding: 6px 8px; font-weight: bold; }.diag-table { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 10pt; }.photo-label { font-size: 8pt; color: #666; margin-top: 4px; text-transform: uppercase; }.photo-item img { width: 100%; border-radius: 4px; border: 1px solid #ddd; }.photo-item { text-align: center; }.photos-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; }.info-label { color: #666; min-width: 140px; }.info-row { display: flex; gap: 8px; font-size: 10pt; }.info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }.section-title { font-size: 12pt; font-weight: bold; color: #111; border-bottom: 2px solid #daa520; padding-bottom: 4px; margin-bottom: 12px; }.section { margin-bottom: 24px; }.content { padding: 24px 30px; }.header .boutique { font-size: 9pt; opacity: 0.7; margin-top: 4px; }.header h1 { font-size: 18pt; font-weight: 300; letter-spacing: 2px; }.header { background: #111; color: #fff; padding: 20px 30px; display: flex; justify-content: space-between; align-items: center; }body { font-family: Arial, sans-serif; font-size: 11pt; color: #222; }* { box-sizing: border-box; margin: 0; padding: 0; }<style>
                        <meta charset="UTF-8"><head>